sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.4.7"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  - haxelib run travix flash
  - haxelib run travix java
  - haxelib run travix cpp -lib hxcpp
  - haxelib run travix cs
  - haxelib run travix php
